# Generated by Django 4.0.2 on 2022-04-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='help',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
