# Generated by Django 4.0.2 on 2022-04-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_remove_answer_submitted_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='slug',
            field=models.SlugField(blank=True, max_length=10),
        ),
    ]
