# Generated by Django 4.0.2 on 2022-04-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_question_correct_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('-created',)},
        ),
    ]
