# Generated by Django 4.0.2 on 2022-04-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_alter_test_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
